---
title: Institute of Foriegn Language
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://y7kim.github.io
baseurl: https://iflbathinda.in/
email: iflbathinda@gmail.com
description: IFL( Institute of Foreign Language) - The Complete English Institute,
  specifically To prepare students for IELTS and Spoken English.
people:
- name: Bhavana Bhatti
  pic: 1
  position: Faculty member
  social:
  - title: twitter
    url: 
  - title: facebook
    url: 
  - title: stack-overflow
    url: 
- name: Puninder Gill
  pic: 2
  position: Faculty Member
  social:
  - title: twitter
    url: 
  - title: facebook
    url: 
  - title: linkedin
    url: 
social:
- title: instagram
  url: https://www.instagram.com/ifl_institute/
- title: facebook
  url: https://www.facebook.com/IFLIELTSBATHINDA
- title: youtube
  url: https://www.youtube.com/channel/UCDe37_oFKHxcd2JRpDnk__A
address:
- line: First floor Mehta computers ,street no. 17 .ajit road, BTI
- line: 9417269093 , 8054420536
markdown: kramdown
permalink: pretty
